version: 5.2.1-{build}
branches:
  except:
  - gh-pages
  - data
  - regression_test
before_build:
- cmd: nuget restore
build:
  project: Trifolia.sln
  verbosity: minimal
test:
  assemblies:
    only:
    - Trifolia.Test.dll
  categories:
    except:
    - FHIR3_E2E
notifications:
- provider: Email
  to:
  - sean.mcilvenna@lantanagroup.com
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false